### ISSUE TITLE
Permission errors if RI is installed to Program Files and not run as admin

### ISSUE THREAD

**Issue by ngyikp** [Vi014/RI-Mod-Manager#5]
If RI is installed to Program Files (not recommended for old games that store user data next to the EXE, but might happen on some game distributor installers), and the mod manager is launched without admin rights, then no file moving/edits would be possible.

Suggestion is to catch the error and suggest re-running the mod manager as admin.

**Comment by Vi014** [comment]
Added try-catch blocks on all instances of file moving and/or editing
